<a href="https://colab.research.google.com/github/eman-kom/tensorflow-fundamentals/blob/main/00_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [3]:
scalar = tf.constant(200)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=200>, 0)

In [4]:
vector = tf.constant([200,500])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200, 500], dtype=int32)>, 1)

In [6]:
matrix = tf.constant([
    [10, 7],
    [7, 10]
])

matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)