<a href="https://colab.research.google.com/github/eman-kom/tensorflow-fundamentals/blob/main/00_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [35]:
scalar = tf.constant(200)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=200>, 0)

In [36]:
vector = tf.constant([200,500])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200, 500], dtype=int32)>, 1)

In [37]:
matrix = tf.constant([
    [10, 7],
    [7, 10]
])

matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [38]:
tensor = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
])

tensor, tensor.shape, tensor.ndim

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]], dtype=int32)>, TensorShape([2, 3, 3]), 3)

In [39]:
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor = tf.Variable([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [40]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [41]:
rand_1 = tf.random.Generator.from_seed(20)
tensor_1 = rand_1.normal(shape=(3, 2))

rand_2 = tf.random.Generator.from_seed(20)
tensor_2 = rand_2.normal(shape=(3, 2))

tensor_1, tensor_2, tensor_1 == tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [42]:
rand_3 = tf.random.Generator.from_seed(20)
tensor_3 = rand_3.normal(shape=(3,3))
tensor_4 = tf.random.shuffle(tensor_3, seed=19)
tensor_3, tensor_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ,  0.86754173],
        [-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ],
        [ 0.88051325, -1.6833194 ,  0.86754173]], dtype=float32)>)

In [43]:
ones = tf.ones([3, 3])
zeros = tf.zeros([2, 3, 4, 5])
ones, zeros

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [44]:
zeros.shape, zeros.ndim, tf.size(zeros)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [45]:
zeros[:2, :2 :, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
ones_1 = ones[..., tf.newaxis]
ones_2 = tf.expand_dims(ones, axis=-1)
ones_1 == ones_2

<tf.Tensor: shape=(3, 3, 1), dtype=bool, numpy=
array([[[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]]])>

In [47]:
ones_3 = tf.multiply(ones, 20)
ones_4 = ones * 20
ones_3, ones_4, ones_3 == ones_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[20., 20., 20.],
        [20., 20., 20.],
        [20., 20., 20.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[20., 20., 20.],
        [20., 20., 20.],
        [20., 20., 20.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [48]:
tf.matmul(ones_3, ones_4), ones_3 @ ones_4, tf.matmul(ones_3, ones_4) == ones_3 @ ones_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1200., 1200., 1200.],
        [1200., 1200., 1200.],
        [1200., 1200., 1200.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1200., 1200., 1200.],
        [1200., 1200., 1200.],
        [1200., 1200., 1200.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [49]:
tensor_2.numpy()

array([[ 0.88051325, -1.6833194 ],
       [ 0.86754173, -0.19625713],
       [-1.322665  , -0.02279496]], dtype=float32)

In [50]:
tf.reshape(tensor_2, [1,6]).numpy()

array([[ 0.88051325, -1.6833194 ,  0.86754173, -0.19625713, -1.322665  ,
        -0.02279496]], dtype=float32)

In [51]:
tf.transpose(tensor_2).numpy()

array([[ 0.88051325,  0.86754173, -1.322665  ],
       [-1.6833194 , -0.19625713, -0.02279496]], dtype=float32)

In [52]:
A = tf.constant([1.3, 2.4])
B = tf.constant([1, -3])
A, B

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.3, 2.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, -3], dtype=int32)>)

In [53]:
C = tf.cast(B, tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1., -3.], dtype=float16)>

In [54]:
D = tf.abs(C)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 3.], dtype=float16)>

In [55]:
import numpy as np
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 29, 48, 93, 60,  4, 61, 42, 34,  1, 61, 76, 56, 27, 95, 80, 65,
       91, 77, 25, 74, 90, 80, 89, 70, 43, 28,  5, 54, 17, 41, 96, 10, 27,
       52, 95, 90, 85, 22, 85, 61, 10, 44, 61, 99, 58,  8, 60, 34, 36])>

In [56]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [57]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [58]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [59]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2681>

In [60]:
max_idx = tf.argmax(E)
max_idx, E[max_idx]

(<tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [61]:
min_idx = tf.argmin(E)
min_idx, E[min_idx]

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>)

In [62]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [63]:
tf.one_hot(some_list, depth=4, on_value="A", off_value="B")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'A', b'B', b'B', b'B'],
       [b'B', b'A', b'B', b'B'],
       [b'B', b'B', b'A', b'B'],
       [b'B', b'B', b'B', b'A']], dtype=object)>

In [64]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [65]:
!nvidia-smi

Sun May 22 11:03:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    27W /  70W |    432MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Exercise

In [66]:
scalar = tf.constant(3)
vector = tf.constant([4, 5])
matrix = tf.constant([[6, 7], [8, 9]])
tensor = tf.constant([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [67]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [68]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [69]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [70]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [74]:
rand_tensor_1 = tf.random.uniform([5, 300], 0, 1)
rand_tensor_2 = tf.random.uniform([5, 300], 0, 1)
rand_tensor_1, rand_tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.47462285, 0.36573255, 0.5642507 , ..., 0.61977243, 0.3335327 ,
         0.77530766],
        [0.49852574, 0.09348822, 0.49192357, ..., 0.958521  , 0.7543241 ,
         0.14554691],
        [0.37736607, 0.46199822, 0.47617435, ..., 0.01512754, 0.45751417,
         0.5183686 ],
        [0.13938308, 0.11055255, 0.37860966, ..., 0.75129306, 0.7767854 ,
         0.6139027 ],
        [0.57955587, 0.01206934, 0.28267395, ..., 0.1884836 , 0.8297206 ,
         0.03034651]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.37317038, 0.85074294, 0.78078854, ..., 0.11412287, 0.14165771,
         0.5546483 ],
        [0.45275354, 0.37588334, 0.9966302 , ..., 0.55906546, 0.17245543,
         0.5007535 ],
        [0.3683983 , 0.92091477, 0.5029546 , ..., 0.91071486, 0.65447605,
         0.20366037],
        [0.8976356 , 0.5563369 , 0.3893677 , ..., 0.2176677 , 0.14356375,
         0.75923467],
        [0.52352

In [76]:
matmul = tf.matmul(rand_tensor_1, tf.transpose(rand_tensor_2))
matmul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.34582 , 69.332565, 70.67053 , 69.3596  , 67.758194],
       [81.48873 , 76.32912 , 75.23307 , 73.000305, 74.910835],
       [73.68324 , 71.22043 , 72.00112 , 69.25948 , 69.82572 ],
       [79.14156 , 71.20945 , 77.09881 , 75.13087 , 73.521576],
       [75.71764 , 69.20613 , 72.97666 , 70.478   , 69.17216 ]],
      dtype=float32)>

In [80]:
tensordot = tf.tensordot(rand_tensor_1, tf.transpose(rand_tensor_2), 1)
tensordot

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.34582 , 69.332565, 70.67053 , 69.3596  , 67.758194],
       [81.48873 , 76.32912 , 75.23307 , 73.000305, 74.910835],
       [73.68324 , 71.22043 , 72.00112 , 69.25948 , 69.82572 ],
       [79.14156 , 71.20945 , 77.09881 , 75.13087 , 73.521576],
       [75.71764 , 69.20613 , 72.97666 , 70.478   , 69.17216 ]],
      dtype=float32)>

In [81]:
tensordot == matmul

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [84]:
tensor_minmax = tf.random.uniform([224, 224, 3], 0, 1)
tensor_minmax

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.54107845, 0.14055383, 0.72050786],
        [0.12890339, 0.81770194, 0.06995344],
        [0.425411  , 0.4978032 , 0.7769779 ],
        ...,
        [0.6145501 , 0.25194395, 0.98248756],
        [0.55646133, 0.3664018 , 0.7445215 ],
        [0.6781268 , 0.09148419, 0.33408105]],

       [[0.3389088 , 0.23109436, 0.6442139 ],
        [0.12672365, 0.07442689, 0.03182197],
        [0.068892  , 0.96129346, 0.51912296],
        ...,
        [0.14066231, 0.35682416, 0.2085923 ],
        [0.69592977, 0.8131771 , 0.00588477],
        [0.70184815, 0.64016294, 0.0747571 ]],

       [[0.27589476, 0.23826325, 0.19162822],
        [0.14873385, 0.21481895, 0.4211197 ],
        [0.6412494 , 0.13262641, 0.51079094],
        ...,
        [0.82844925, 0.5149312 , 0.04949689],
        [0.5368755 , 0.697265  , 0.19235706],
        [0.9229592 , 0.73914945, 0.17850482]],

       ...,

       [[0.03120029, 0.72602725, 0.92950666],
        [0.33

In [87]:
tf.reduce_min(tensor_minmax), tf.reduce_max(tensor_minmax)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.887581e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999654>)

In [90]:
tensor_squeeze = tf.random.uniform([1, 224, 224, 3], 0, 1)
tensor_squeeze.shape

TensorShape([1, 224, 224, 3])

In [91]:
tf.squeeze(tensor_squeeze).shape

TensorShape([224, 224, 3])

In [94]:
flat_list = tf.constant([1,2,3,4,5,6,7,8,9,10])
tf.argmax(flat_list)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [95]:
tf.one_hot(flat_list, depth=len(flat_list))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>