<a href="https://colab.research.google.com/github/eman-kom/tensorflow-fundamentals/blob/main/00_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [3]:
scalar = tf.constant(200)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=200>, 0)

In [4]:
vector = tf.constant([200,500])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200, 500], dtype=int32)>, 1)

In [6]:
matrix = tf.constant([
    [10, 7],
    [7, 10]
])

matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [7]:
tensor = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
])

tensor, tensor.shape, tensor.ndim

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]], dtype=int32)>, TensorShape([2, 3, 3]), 3)

In [11]:
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor = tf.Variable([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
rand_1 = tf.random.Generator.from_seed(20)
tensor_1 = rand_1.normal(shape=(3, 2))

rand_2 = tf.random.Generator.from_seed(20)
tensor_2 = rand_2.normal(shape=(3, 2))

tensor_1, tensor_2, tensor_1 == tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [25]:
rand_3 = tf.random.Generator.from_seed(20)
tensor_3 = rand_3.normal(shape=(3,3))
tensor_4 = tf.random.shuffle(tensor_3, seed=19)
tensor_3, tensor_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ,  0.86754173],
        [-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ],
        [ 0.88051325, -1.6833194 ,  0.86754173]], dtype=float32)>)

In [32]:
ones = tf.ones([3, 3])
zeros = tf.zeros([2, 3, 4, 5])
ones, zeros

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [33]:
zeros.shape, zeros.ndim, tf.size(zeros)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
zeros[:2, :2 :, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
ones_1 = ones[..., tf.newaxis]
ones_2 = tf.expand_dims(ones, axis=-1)
ones_1 == ones_2

<tf.Tensor: shape=(3, 3, 1), dtype=bool, numpy=
array([[[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]]])>

In [41]:
ones_3 = tf.multiply(ones, 20)
ones_4 = ones * 20
ones_3, ones_4, ones_3 == ones_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[20., 20., 20.],
        [20., 20., 20.],
        [20., 20., 20.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[20., 20., 20.],
        [20., 20., 20.],
        [20., 20., 20.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [44]:
tf.matmul(ones_3, ones_4), ones_3 @ ones_4, tf.matmul(ones_3, ones_4) == ones_3 @ ones_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1200., 1200., 1200.],
        [1200., 1200., 1200.],
        [1200., 1200., 1200.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1200., 1200., 1200.],
        [1200., 1200., 1200.],
        [1200., 1200., 1200.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)